name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose up to create containers
        run: docker-compose up --build -d
      - name: Sleep to give time for MongoDB to set itself up
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - name: Run tests
        run: docker-compose run --rm server yarn test --forceExit
