name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build server image
        run: docker-compose build
      - name: Start mongo service
        run: docker-compose up mongo -d
      # - name: Sleep to give time for MongoDB to set itself up
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: "5s"
      - name: Run tests
        run: docker-compose run --rm server yarn test --forceExit
